# ARCHIVO DE SECRETOS - NO COMPARTIR NI SUBIR A GIT
# Este archivo contiene llaves sensibles para el proyecto RutaGo.

GOOGLE_WEB_CLIENT_ID=175264872585-abombvqq36bqqeet86onnhkf7uep6c60.apps.googleusercontent.com
